version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: proxy-reverso
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./certbot-data:/etc/letsencrypt:ro
    networks:
      - omd-network
      - alura-tecboard
    command: '/bin/sh -c ''nginx -g "daemon off;" || (nginx -t && nginx -g "daemon off;")'''

  # Container para obter e renovar certificados
  certbot:
    image: certbot/certbot
    container_name: certbot-manager
    restart: always
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./certbot-data:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do if [ ! -d /etc/letsencrypt/live/planoacao.portfolio.ivansantos.dev ]; then certbot certonly --webroot -w /var/www/certbot --email contato@ivansantos.dev --agree-tos --no-eff-email --force-renewal -d planoacao.portfolio.ivansantos.dev; fi; if [ ! -d /etc/letsencrypt/live/tecboard.portfolio.ivansantos.dev ]; then certbot certonly --webroot -w /var/www/certbot --email contato@ivansantos.dev --agree-tos --no-eff-email --force-renewal -d tecboard.portfolio.ivansantos.dev; fi; certbot renew --quiet; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - omd-network
      - alura-tecboard

networks:
  omd-network:
    external: true
  alura-tecboard:
    external: true
