version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: omd-frontend
    restart: always
    networks:
      - omd-network

  backend:
    build:
      context: ./backend
    container_name: omd-backend
    restart: always
    networks:
      - omd-network

  nginx:
    image: nginx:latest
    container_name: omd-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/www:/var/www/certbot
      - ./certbot-data:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - omd-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./certbot-data:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email contato@ivansantos.dev --agree-tos --no-eff-email -d planoacao.portfolio.ivansantos.dev
    networks:
      - omd-network

networks:
  omd-network:
    driver: bridge
